module.exports = [
    "Spicy carne asada with a pico de gallo sauce",
    "Shredded chicken tacos with a mango chilli lime salsa",
    "Cheesecake with a passion fruit swirl sauce",
    "Barbecue pulled pork on sourdough bread",
    "Roast turkey with a honey and herb marinade and roasted vegetables",
    "Banana walnut loaf with chocolate chips",
    "Seared scallops",
    "Pan seared venison with fruit salad side",
    "Caramelised apple pie with vanilla ice cream",
    "Cajun spiced chicken wings",
    "Mild cheddar",
    "Lemon tart",
    "Ancho chilli beef taco",
    "Chocolate gateaux",
    "Rum poached pears with dark chocolate sauce",
    "Smoked cured beef",
    "Smoked aubergine tapenade with rye bread",
    "Beer affogato - 1/3 glass of Paradox with a scoop of vanilla ice cream",
    "Sashimi",
    "Pan roasted poussin with spring veg",
    "Lemon and thyme panna cotta",
    "Quince cheese",
    "Shredded chicken and mango salsa taquitos",
    "Poached pear",
    "Spicy chicken tikka masala",
    "Grilled chicken quesadilla",
    "Caramel toffee cake",
    "Lamb and root vegetable stew",
    "Warm goats cheese salad",
    "Raisin rum cake",
    "Oysters",
    "Hickory smoked ham",
    "Rocky Road",
    "Arrabiata pasta with grilled prawns",
    "Mexican spiced chicken with hot sauce",
    "Orange marmalade thumb print cookie",
    "Fresh crab with lemon",
    "Garlic butter dipping sauce",
    "Goats cheese salad",
    "Creamy lemon bar doused in powdered sugar",
    "Spicy seafood stew",
    "French onion soup",
    "Mexican wedding cake (cookies)",
    "Haggis spring rolls",
    "Honey glazed duck breast",
    "Cranachan",
    "Spicy cajun fried chicken",
    "Pork dumplings with rich soy sauce",
    "Cinnamon carrot cake with creamy cheese frosting",
    "Poached sole fillet with capers",
    "Summer fruit salad",
    "Banana split",
    "Spicy mexican meatball stew",
    "Habenero and mango pulled pork tacos",
    "Spiced pumpkin pie with chocolate whipped cream",
    "Poached eggs and smoked salmon",
    "Salt and pepper squid",
    "Key Lime Pie",
    "Gooey chocolate brownies",
    "Chicken fried steak with cheesy mash",
    "Spicy chicken empanadas",
    "Stilton on gingerbread biscuits",
    "Pot roasted artichokes",
    "Lamb chops with caramelised figs",
    "Aromatic spicy red thai curry",
    "Sticky spicy barbecue ribs with a strong blue cheese dipping sauce",
    "Creamy warm baked goats cheese salad",
    "Smoked venison sausage",
    "Very mature Cheddar",
    "Fettucine alfredo",
    "Spicy pork sausages with red potato mash",
    "Turnip beef stew with crusty fresh baked bread",
    "Summer berry cheesecake",
    "Cheddar cheese melt on crisp rye toast",
    "Moroccan chicken tangine",
    "Cheesecake topped with kiwi",
    "Chorizo cooked in red wine",
    "Rib eye steak with a compound butter",
    "Baked Alaska",
    "Duck liver paté",
    "Mutton stew",
    "Kirsch chocolate truffles",
    "Herbal roast beef with a cranberry jus",
    "Baked honey glazed ham with dark fruit sauce",
    "Dark fruit cake",
    "Moules frites",
    "Thai green curry",
    "Lemon posset",
    "Chocolate crème brûlée with raspberries",
    "Thyme, rosemary and black pepper rubbed roast beef served with fried green beans",
    "Angus beef cheeseburger",
    "Earthy mushroom pasta",
    "Lobster thermidor",
    "Pan fried Foie Gras",
    "Vanilla bean white chocolate",
    "Grilled fish salad",
    "Angelfood cake",
    "Pad Thai",
    "Vegetable egg scramble",
    "Margherita pizza",
    "Fresh berry crisp tart",
    "Spicy chicken and chilli verde sauce enchiladas",
    "Smoked chorizo and strong cheese board",
    "Spicy wings with blue cheese dip",
    "Pan seared scallops with a chilli sauce",
    "Creamy chocolate and caramel cheesecake",
    "Charred apricot salad",
    "Whole baked reblochon",
    "Salted caramel crème brûlée",
    "Pastrami",
    "Swiss and horseradish sandwich",
    "Sharp cheddar cheese and onion/ raisin chutney",
    "Peanut brittle",
    "Haggis bon bons",
    "Rosemary and lemon roast chicken",
    "Oatmeal and cranberry cookies",
    "Baked brown butter lobster",
    "Apple crumble and custard",
    "Coffee carrot cake",
    "Kedgeree",
    "Scotch broth with sourdough bread",
    "Clootie dumpling",
    "Strong blue cheese",
    "Chicago style hot links",
    "Tom yum soup",
    "Andhra chicken pickle curry",
    "Butterscotch tart",
    "Strong gorgonzola endive salad",
    "Sirloin steak with fresh salad",
    "Cinnamon poached pears",
    "Thick cut salami pieces on tiger bread",
    "Chilli spiced pork pie",
    "Poached pear and blue cheese crumble",
    "Beef mahaca on corn tortillas",
    "Chilli and dark chocolate tart",
    "Epoisses cheese",
    "Applewood cheddar bacon beef burger",
    "Roasted garlic camembert",
    "Parmesan truffles",
    "Braised pheasant",
    "Caramel sauce and hot fudge",
    "Aged cheddar with honey and raspberry chutney",
    "Rich beef stew with winter vegetables and a dash of honey",
    "Scottish raspberry cranachan parfait",
    "Truffle oil filet mignon",
    "Sweet sticky beef brisket",
    "Chocolate and dark cherry fondant",
    "Venison with cacao nibs",
    "Apple upside-down cake",
    "Toffee marshmallow pie",
    "Crayfish with a chilli, coriander infused butter dip",
    "Smörgås with cream topping",
    "Cardamom cake with powder sugar and cloudberry jam",
    "Warm blackberry pie",
    "Vinegar doused fish and chips",
    "Aromatic korma curry with lemon and garlic naan",
    "Lemon and herb salmon",
    "Sharp cheddar with mango chutney",
    "Shredded chicken tacos with pico de gallo",
    "Grilled halloumi salad with orange and pomegranate vinaigrette",
    "Baked Camembert with smoked garlic, and salt and pepper wheat crackers",
    "Crab cakes with lemon cream and herb dipping sauce",
    "Grilled salmon with a herb and citrus infused butter",
    "Basil, lemon and pine nut angel hair pasta with grilled chicken",
    "Vietnamese squid salad",
    "Chargrilled corn on the cob with paprika butter",
    "Strawberry and rhubarb pie",
    "Havarti cheese",
    "Cajun spiced fried chicken",
    "Lemon squares",
    "Grilled portabello mushroom burger",
    "Chicken sausages with creamy mash",
    "Caramel and banana meringue pie",
    "Coffee dusted venison loin",
    "Memphis-style beef short ribs",
    "Chocolate orange brownies",
    "Herring rollmops",
    "Chicken schnitzel",
    "Gin & elderflower jelly",
    "Roasted wood pigeon with black pudding",
    "Pan seared venison fillet with juniper sauce",
    "Apricot coconut cake",
    "Candied almond and blue cheese rocket salad",
    "Chicken Tikka Madras",
    "Pecan pie",
    "California sushi rolls with fresh crab and wasabi infused soy sauce",
    "Spicy chilli and coriander Thai beef stew",
    "Carrot and coriander rich cake",
    "Salt baked cod with lemon and dill butter",
    "Beef, oyster and ale pie",
    "Apple and rosemary tart",
    "Calves' liver with onion relish",
    "Coq au vin",
    "S'mores",
    "Kippers and poached eggs",
    "Slow cooked lamb shoulder with mint sauce",
    "Apple and blackcurrant cobbler",
    "Honey glazed ham with spicy roasted carrots",
    "Mature cheddar with spicy chutney",
    "Peach cobbler",
    "Seared steak with a peppercorn sauce",
    "Strong blue cheese and oatcakes",
    "Chocolate cheesecake",
    "Beef satay skewers",
    "Venison & cranberry pie",
    "Blackberry mocha gateaux",
    "Caramelised scallops with burnt apple puree",
    "Blackened Cajun chicken",
    "Blondies with chocolate fudge sauce",
    "Lapin aux pruneaux (braised rabbit with prunes)",
    "Gouda cheese",
    "Dark chocolate truffles",
    "Classic American cheeseburger",
    "Chilli chocolate bars",
    "Pheasant paté",
    "Roast duck in a cherry glaze",
    "Chocolate torte with a dark fruit compote",
    "Beer roasted chicken",
    "Ham and pineapple pizza",
    "Chocolate cake drizzled with orange",
    "Blue cheese beef burger",
    "Glazed short ribs",
    "Chocolate cake",
    "Coriander & chilli crab cakes",
    "Goats cheese salad with walnuts, radish and blood orange",
    "Pistachio cake",
    "Stilton Blue featured cheese platter",
    "Dark bitter chocolate torte",
    "Scotch bonnet beef chilli",
    "Caramelized onion and steak pie",
    "Chicken Khua Kling (dry Thai curry)",
    "Lemon drizzle cake",
    "Spicy green chilli and lemongrass chicken thai curry",
    "Sharp cheddar cheese and crackers",
    "Ginger and orange zest cookies",
    "Spicy jalapeño & seared steak fajitas",
    "Grilled spicy corn with feta crumbles",
    "Blueberry pie",
    "Tofu pad Thai with fresh lime juice and coriander",
    "Fish tacos with avocado",
    "Key lime pie",
    "Baja style fish tacos",
    "Jerk chicken",
    "Apple crumble",
    "Grilled king prawns with a chilli lime sauce",
    "Blue cheese burger",
    "Flourless chocolate ginger cake",
    "Blue cheese & onion tart",
    "Goan goat curry",
    "Sugar-poached kumquat rice pudding",
    "Blackened cajun beef",
    "Cave-aged cheddar",
    "Flourless chocolate chilli cake",
    "Monterey Jack stuffed grilled jalepenos",
    "Barbecue corn and steak fajita seasoned wrap",
    "Cinnamon & white chocolate churro",
    "Game terrine",
    "Spiced fruit cake",
    "Chocolate, cherry and hazelnut mousse",
    "Phall Curry",
    "Pork burrito with a habanero and mango chilli salsa",
    "Ginger and grapefruit poundcake",
    "Grilled chicken salad with bacon and avocado",
    "Red pepper houmous and flat bread",
    "Matcha green tea cake",
    "Venison stroganoff",
    "Chilli dog",
    "Toffee chocolate cheesecake",
    "Tandoori lamb with pomegranate",
    "Beef Wellington with a red wine jus",
    "Raspberry chocolate torte",
    "Huevos rancheros",
    "Mild coriander and chilli chicken curry",
    "Panna cotta with an orange and raspberry sauce",
    "Rosemary and thyme grilled chicken",
    "Light vegetable and herb soup with toasted rye bread",
    "Earl Grey ice cream with a lavender sauce",
    "Steak taquitos with spicy mole sauce",
    "Herb roasted duck with a fruit sauce",
    "Dark chocolate and chilli flourless cake",
    "Honey glazed ham with pineapple",
    "Spicy wings with blue cheese sauce",
    "Blackberry pie with vanilla ice cream",
    "Black bean and avocado enchiladas with mole sauce",
    "Mexican spiced cheddar cheese",
    "Pancakes with maple syrup",
    "Spiced cranberry turkey",
    "Sriracha covered brussel sprouts",
    "Ginger rice pudding",
    "Beef chilli made with cocoa powder",
    "Dark chocolate covered bacon",
    "Rich espresso tiramisu",
    "Smokey sweet pulled brisket",
    "Espresso crusted venison with a dark cherry jus",
    "Affogato with vanilla ice cream",
    "Falafel and hummus pitta wrap",
    "Bratwurst with spicy relish",
    "Strawberry tart",
    "Flame grilled steak",
    "Venison and Winter vegetable stew",
    "Maple bacon chocolate cupcakes",
    "Bratwurst sausage with spicy mustard",
    "Fried American bacon with chilli flakes added to the top",
    "Dark chocolate chip cookies",
    "Spicy fish tacos",
    "Bacon mac 'n' cheese",
    "Pear crumble",
    "Sweet pork Chinese dumplings",
    "Caramelised onion venison burger",
    "Banoffee pie",
    "Spicy Asian-style noodles",
    "Smokey chipotle beef brisket tostada",
    "Sweet potato pie",
    "Watermelon and feta salad with balsamic reduction",
    "Grilled chicken with a chilli soy sauce marinade",
    "Crème brûlée with apricot coulis",
    "Rosemary and thyme marinated venison",
    "Fish and chips",
    "Lavender chocolate chip cookies",
    "Hot spiced barbecue chicken wings",
    "Orange sesame chicken",
    "Chocolate fondue with fruit",
    "Jamaican jerk chicken",
    "Hot dog with grilled onions and spicy ketchup",
    "Shortbread and raspberry jam thumbprint cookie",
    "Crispy bacon on flat bread",
    "Glazed ham with crackling coating",
    "Popcorn caramel and chocolate cake",
    "Grilled vegetable and chicken teriyaki skewers",
    "Chilli covered burger (Sloppy Joe)",
    "Candied bacon topped chocolate cheesecake",
    "Fried crab cakes with avocado salsa",
    "Spicy shredded pork roll with hot dipping sauce",
    "Arrabiata pasta",
    "Mulled cheddar",
    "Toasted almond cake",
    "Citrus salad with balsamic dressing",
    "Lobster",
    "Ginger and orange cookies",
    "Roasted garlic and chilli infused camembert cheese",
    "Korean style chicken wings",
    "Chocolate milk shake",
    "Roast beef",
    "Roasted butternut squash",
    "Hazelnut brittle",
    "Blue cheese",
    "Flourless chocolate cheesecake",
    "Mussels with a garlic and herb sauce",
    "Crab melt sandwich",
    "Shortbread cookies",
    "Spiced and blackened cajun chicken",
    "Pork belly vindaloo",
    "Rhubarb pie",
    "Fårikål (mutton stew) with a spicy twist",
    "Fenalår (salted cured lamb)",
    "Krumkake with lingonberry jam",
    "Spiced carrot and coriander soup",
    "Spicy chilli king prawns",
    "Orange zest tart",
    "Cured Spanish ham",
    "Steak pasty",
    "Black cherry tart",
    "Grilled salmon with a light lemon sauce",
    "Lobster bisque",
    "Cheesecake with raspberry (or peach/passion fruit) sauce",
    "Mature cheddar with red onion chutney",
    "Honey glazed ham",
    "Chocolate caramel drizzled sponge cake",
    "Lamb chops with a blueberry reduction",
    "Cured ham and strong mulled cheddar board",
    "Warm blueberry pie",
    "Stilton",
    "Pan seared steak",
    "Dark Chocolate Fondant",
    "Brisket burnt ends",
    "Candied bacon French toast",
    "Coco Pops (add stout to cereal)",
    "Fried brie bites",
    "American cheese burger",
    "Poached apple tart",
    "Spicy paella",
    "German bratwurst with spicy mustard dip and vinaigrette salad",
    "Creamy eggs benedict",
    "Roast beef with spicy jus",
    "Ginger bread cookies",
    "Orange tart",
    "Spicy crab cakes",
    "Spicy cucumber and carrot Thai salad",
    "Sweet filled dumplings",
    "Roasted duck",
    "Gorgonzola and rye nut bread with smoked honey ham",
    "Raspberry coffee cheesecake",
    "Grilled rib-eye steak",
    "Baked curry chickpea snacks",
    "Chocolate and walnut brownie",
    "Mozzarella and tomato baked chicken",
    "Spiced shrimp salad",
    "Strawberry cheescake",
    "Oak chip smoked salmon",
    "Sticky spicy barbecue ribs",
    "Scottish tablet",
    "Spicy Vietnamese vermicelli salad",
    "Spicy fish tacos with mango chilli",
    "Banana bread",
    "Spicy carne asada with black beans and Mexican Rice",
    "Pork smothered in mole sauce",
    "Chocolate covered espresso beans",
    "Maple syrup drizzled chocolate chip pancakes",
    "Fried bacon with crispy honeycomb bits",
    "Coffee cake",
    "Aged Stilton",
    "Flaky pastry beef pie and sweet potato mash",
    "Chocolate pecan praline cake",
    "Russian mini pork pies",
    "Beef Stroganoff",
    "Chocolate and fruit cake",
    "Pulled pork",
    "Millionaire's shortbread",
    "Margherita pizza with chili flakes",
    "Spicy Thai peanut satay",
    "Panna cotta with a grapefruit tuile",
    "Spicy black bean and chicken tortilla soup",
    "Spicy lamb tikka masala",
    "Fruity bread pudding",
    "Tuna sushi roll with spicy mayonnaise sauce",
    "Pineapple upside down cake",
    "Grilled lamb chops with a fruit reduction",
    "Ginger and chilli beef stir fry",
    "Passionfruit soufflé",
    "Spicy beef and Mexican black bean burger",
    "Poached cinnamon apple muffins",
    "Chicken satay",
    "Thai fishcakes",
    "Honey and almond sponge cake",
    "Beetroot and blood orange salad",
    "Coriander and mango grilled steak tacos",
    "Orange sherbet ice cream",
    "Korvapuusti (cinnamon and cardamom buns)",
    "Spicy orange chicken marmalade served with potato bread",
    "Sea buckthorn cheesecake",
    "Crab roll sushi with strawberries",
    "Artichoke hearts and chicken melt",
    "Caprese salad (mozzarella, tomato, basil, black pepper and sea salt)",
    "Halibut with caper brown butter",
    "Creamy gorgonzola and satsuma salad",
    "Spicy Daal with garlic naan bread",
    "Stilton tart",
    "Caramelised onion and ham foccacia",
    "Dark fruit crumble",
    "Seared lemon and herb salmon",
    "Crab linguine",
    "Almond biscotti",
    "Smoked bratwurst and mustard",
    "Chargrilled steak",
    "Grilled pineapple",
    "Strawberry and citrus salad",
    "Fish corn tacos with pomegranate salsa",
    "Summer berry fruit parfait",
    "Chilli con carne",
    "Pepper jack cheese burger on a brioche bun",
    "Strong cheddar fondue",
    "Pork chops with spicy orange marmalade",
    "Rich crème brûlée",
    "Spicy chicken skewers",
    "Fish tacos with hot sauce",
    "Lemon pound cake with a ice sugar glaze",
    "Roast chicken with vegetables and wild rice",
    "Fresh pico de gallo with corn tortilla",
    "Carrot cake",
    "Mexican ceviche",
    "Blue cheese crumbled over wedges",
    "Gooey lemon bar",
    "Korean barbecue nachos",
    "Beef pho soup",
    "Waffles with caramelised apple and powdered sugar",
    "12hr smoked brisket",
    "Chocolate pistachio cakes",
    "Dulche de leche",
    "Fresh seared tuna and rocket salad",
    "Lemon meringue pie",
    "Baked chicken with yuzu reduction",
    "Chunky orange marmalade on toast",
    "Prawn toast with sweet chilli sauce",
    "Jalapeño and cream cheese poppers",
    "Asparagus pesto pasta",
    "Bacon and maple syrup cupcakes",
    "Chinese chicken salad",
    "Lemon grilled halibut",
    "Bacon sandwich with brown sauce",
    "20hr smoked brisket",
    "Chocolate fudge ice cream",
    "Coconut beef red curry",
    "Butternut squash soup with toasted almonds",
    "Chocolate coated macaroons",
    "Habanero spicy chicken wings with ranch sauce",
    "Jalapeño chilli and chicken quesadillas",
    "New York style cheesecake",
    "Mississippi style pork ribs",
    "Chunky mild spice beef stew",
    "Chocolate chunky cookies",
    "Jerk spiced goat",
    "Tonkotsu Ramen",
    "Gingerbread",
    "Celery and stilton soup",
    "Salted caramel soufflé",
    "Scones with cloudberry jam",
    "Oysters with a chilli and dill sauce",
    "Rhubarb tart",
    "Chicken fajita spiced monteray jack quesadillas",
    "Chilli lime and coriander marinated king prawn cocktail",
    "Margarita key lime pie",
    "Cheddar cheese toastie on dark rye",
    "Lamb samosas with chilli dipping sauce",
    "Cheesecake",
    "Lavender and thyme roast beef",
    "Spicy kung po chicken",
    "Caramel and rose essence cheesecake",
    "Fried teriyaki chicken",
    "Chicken jalfrezi",
    "Chocolate and toffee fondant",
    "Caramelised onion and lightly seared steak",
    "Pulled barbecue brisket",
    "Salted caramel cheesecake",
    "Beef carpaccio",
    "Chilled beetroot soup",
    "Korean watermelon salad",
    "Greek piroshki pies",
    "Poached salmon with salsa verde",
    "Strawberry filo tarts",
    "Mushroom pithivier",
    "Roast pheasant with savoy cabbage",
    "Dark chocolate ganache macaroons",
    "Paella",
    "Smoked dry-cured venison sausage",
    "Potted fresh & smoked salmon",
    "Spiced nut loaf",
    "Lemon poppyseed donuts",
    "Wild rice salad with wild mushrooms",
    "Apple gingerbread pancakes",
    "Christmas Pudding",
    "Grilled fish tacos",
    "Greek salad",
    "Goat's cheese",
    "Charcuterie platter (featuring Italian salami)",
    "Blue cheese wedge salad",
    "Rich dark chocolate volcano cake",
    "Sriracha infused shredded beef",
    "Chipotle steak tacos",
    "Chilli chocolate fondant",
    "Mulled cheddar buffalo burger",
    "Venison with warm spices (cardamom) and sweet potato",
    "Pure vanilla bean ice cream",
    "Summer salad with pickled veg",
    "Sticky barbecue spare ribs",
    "Blueberry and almond tart",
    "Warms goats cheese salad",
    "Trifle or chocolate cake",
    "Roasted pumpkin and mozzarella",
    "Black forrest gateaux",
    "Okra fries",
    "Sea bass ceviche",
    "Sea salt fudge",
    "Aged gouda",
    "German bratwurst sausage",
    "Poached pear fritters",
    "Creamy maple syrup and bacon soup",
    "Chunky chicken and vegetable spiced stew",
    "Pumpkin pie",
    "Pork chop with rosemary chips",
    "Steak tartare",
    "Belgian waffles",
    "Tamale",
    "Salt cod croquettes",
    "Mint cheesecake",
    "Soy and honey glazed mackerel",
    "Moroccan spice lamb shanks",
    "Baklava",
    "Lightly curried spiced chickpea dip",
    "Fried calamari with a mild sauce",
    "Lemon sherbet cookies",
    "Strawberry and basil salad with feta",
    "Lemon baked monkfish",
    "Lamb cutlets with cucumber raita",
    "Pigeon pea dal",
    "Set vanilla custard",
    "Tomato and rosemary palmiers",
    "Bratwurst with sauerkraut",
    "Butternut squash and sage soup",
    "Roast beef and horseradish sandwich",
    "Fudge",
    "Rocket and mozzarella salad with a cracked pepper dressing",
    "Fried halibut with sweet potato fritters",
    "Grapefruit and blood orange tart",
    "Grilled salmon",
    "Mac and cheese fries",
    "Cheesecake with raspberry coulis",
    "King prawn kebabs",
    "Halibut with a mango and tomato salad",
    "Mint chocloate ice cream",
    "Coriander and lime green thai curry",
    "Grapefruit souffle",
    "Smoked chicken wings",
    "Miso ramen",
    "Yuzu cheesecake",
    "Cauliflower pakora with mango chutney",
    "Penne with tomato and smoked cheese",
    "Salted caramel ice cream and peanuts",
    "Jalapeño poppers with blue cheese dip",
    "T-bone steak with fried onions",
    "Carrot cake with cream cheese frosting",
    "Oyster beignets",
    "Beef shin stew",
    "A Shakin' jesse",
    "Reuben sandwich",
    "Halloumi and sweet chili burger",
    "Passionfruit meringue pie",
    "Shrimp aguachile",
    "Mezcal marinated sirloin steak",
    "Basil panna cotta with strawberries",
    "Pesto chicken pizza",
    "Beer braised Brussels sprouts",
    "Crème brûlée",
    "Tuna & salmon sushi (with plenty of wasabi!)",
    "Chipotle chicken burrito",
    "Rhubarb fool with shortbread",
    "Cheese boards",
    "Sashimi sushi",
    "French fries dressed in good oil and salt",
    "Mac and Cheese",
    "Char sui pork buns",
    "Spicy beef empanadas",
    "Cornish Yarg",
    "Vanilla & raspberry panna cotta",
    "Wild boar salami",
    "Jamaican jerk chicken wings",
    "Corn dogs",
    "Strawberry ice cream sundae",
    "Smoked mackerel & radish salad",
    "Ossobuco",
    "Dark chocolate & salted caramel brownie",
    "Cheese covered tater tots",
    "Chicago style hot dog",
    "Beignet",
    "Confit duck with cherry sauce",
    "Cajun ribs",
    "Buttermilk waffles",
    "Baja fish tacos",
    "Green mango salad",
    "Salted butterscotch oatmeal cookies",
    "Buffalo wings with blue cheese dip",
    "Spinach and feta tacos",
    "Triple chocolate chip cookies",
    "Courgette fries",
    "Curried sea bass",
    "Pistachio layer cake",
    "Aubergine and chickpea tagine",
    "Firehouse chili con carne",
    "Vanilla milkshake",
    "Chicken, mango and chili salad",
    "Deep fried coconut prawns",
    "Smoked salmon tostada",
    "Schäufele",
    "Rye apple cake",
    "Ancho pulled beef chilli",
    "Aged cheddar, chickpea & roasted vegetable tagine",
    "Salt beef bagel with mustard & pickles",
    "Pork belly ramen",
    "Beetroot and goats cheese salad",
    "Vegetable Samosas",
    "Thai Green Chicken Curry",
    "Vanilla Panna Cotta",
    "Chicken Katsu",
    "Cheese and Ham Omelette",
    "Pumpkin Pie",
    "Herb-Crusted Baked Cod",
    "Berry and Cream Meringue",
    "Lemon Drizzle Cake",
    "Taleggio and Spinach Tart",
    "Chicken Adobo",
    "Crème Caramel",
    "Tempura Prawns",
    "Soy-Glazed Chicken Thighs",
    "Raspberry Soufflé",
    "Panko-coated Chicken Katsu",
    "Classic Cheddar Ploughmans",
    "Pecan Pie",
    "Game Terrine with Pickles",
    "Fish Tacos",
    "Peach Melba",
    "Steak Pie and Winter Vegetables",
    "Chocolate Torte",
    "Blackcurrant Panna Cotta",
    "Loaded Hamburger and Spicy Fries",
    "Warm Banana Bread",
    "Pineapple Sponge Cake",
    "Crab Cakes",
    "Spicy Bean Burrito",
    "Dundee Fruit Cake",
    "Beef Rendang",
    "Coconut Macaroons",
    "Profiteroles with Chantilly Cream",
    "Jerk Chicken Kebabs with Mango Salsa",
    "Avocado and Citrus Salad",
    "Pineapple Upside Down Cake",
    "Pork Burrito with a Habanero and Mango Chili Salsa",
    "Ginger and Grapefruit Poundcake",
    "Salmon Fishcakes with Rocket Salad",
    "Baked Goat's Cheese",
    "Classic Victoria Sponge",
    "Californian Sushi Roll",
    "Parmesan and Rocket Pizza",
    "Coconut Cake",
    "Cajun Chicken Burger",
    "Baked Brie",
    "Tomato and Herb Bruschetta",
    "Game Terrine",
    "Barbecue-griddled Poussin",
    "Clootie Dumpling",
    "Bratwurst and Mustard",
    "Caraway Roast Pork",
    "Gingerbread Cake",
    "Coriander & Chilli Crab Cakes",
    "Basil Pasta",
    "Caramelised Orange Cheesecake",
    "Chicken Korma",
    "Lobster Tail Salad",
    "Chickpea and Apricot Tagine",
    "Pan-Seared Venison with Blackberries",
    "Fig Tart",
    "Dark Chocolate and Coffee Torte",
    "Char-grilled Lamb Cutlets",
    "BBQ Brisket",
    "Chocolate and Strawberry Mousse",
    "Steak and Kidney Pie",
    "Pork Carnitas",
    "Chocolate Orange Brownies",
    "Goat's Cheese Bruschetta",
    "Pan-Fried Lemon Sole",
    "Baked Peaches with Citrus Fruit Reduction",
    "Habanero Pulled Pork",
    "Choc Chip Cookies,",
    "Black Pudding Croquettes",
    "Lobster Salad",
    "Chicken and Apricot Tagine",
    "Green Thai Curry",
    "Goat's Cheese Salad With Walnuts, Radish And Blood Orange",
    "Pan-fried Lemon Sole",
    "Citrus Salad",
    "Spicy Chilli Prawns",
    "Orange Zest Tart",
    "Lemon Tart",
    "Roast Pheasant With Savoy Cabbage",
    "Chilli Beer Tacos",
    "Dark Chocolate Truffles",
    "Baked Peaches With Citrus Fruit",
    "Soft pretzel with mustard",
    "Hot Smoked Salmon Salad",
    "Rum Fried Banana",
    "Duck Crackling",
    "Coq Au Vin",
    "Oreo Cheesecake",
    "Gingerbread Man",
    "Feta And Tomato Salad With Balsamic Dressing",
    "Raspberry Parfait",
    "Pancakes",
    "Honey Mustard Chicken",
    "Crème Brûlée",
    "Hot Wings And Blue Cheese Dip",
    "Black Pudding Burger",
    "Sticky Toffee Pudding And Salted Caramel Ice Cream",
    "Guacamole And Chips",
    "Coriander Chicken Tostadas",
    "Grilled Halibut",
    "Pickled Herrings",
    "Moules Frites",
    "Grilled Portobello Mushroom Burger",
    "Citrus Salad With Balsamic Dressing",
    "Ginger And Orange Cookies",
    "Salmon Salad",
    "Montery Jack Cheese",
    "Mandarin Cake",
    "Stilton and Walnut Welsh Rarebit.",
    "Cherry Chocolate Cake With Chocolate Whipped Mousse",
    "Simnel Cake",
    "Barbeque and Mustard Beef on Rye Bread",
    "Gooseberry and Plum Compote",
    "Mature Wensleydale",
    "Oysters With a Chilli And Dill Sauce",
    "Raspberry Souffle",
    "White Chocolate and Pistachio Cheesecake",
    "Baked Tilapia With Lemon and Cream Sauce",
    "Vegan Mac and ‘Cheese’",
    "S’mores with smoked marshmallows",
    "Braised rabbit stew",
    "Espresso brownies with burnt sugar ice cream",
    "Roast pork chops",
    "Beef in port stew",
    "Cherry frangipane tart",
    "Steamed cod with ginger and spring onions",
    "Blueberry muffins",
    "Apple and blueberry pie",
    "Spinach and feta salad",
    "Balsamic-glazed salmon",
    "Basil granita",
    "Smoked venison stew",
    "Sloe gin mixer",
    "Black forest gateau",
    "Pork meatballs",
    "Game pie",
    "Grilled goat’s cheese",
    "Peking duck",
    "Pork and coriander stew",
    "Almond pound cake",
    "Grilled sea bass fillet",
    "Sushi maki",
    "Summer fruit pudding",
    "Deep-fried calamari",
    "Paneer skewers with cardamom",
    "Plum cobbler",
    "Stir-fried chicken",
    "Chocolate mousse",
    "Orange polenta cake",
    "Pecan muffins with chocolate ganache",
    "Salted caramels",
    "Hazelnut truffles",
    "Steak",
    "Chicken korma",
    "Lobster salad",
    "Habanero pulled pork",
    "Dark chocolate and coffee torte",
    "Roasted halibut with grapefruit salsa",
    "Butternut squash bisque",
    "+80% Dark chocolate",
    "Thai sweet potato and carrot soup",
    "Peaches and cream",
    "Mole Mexican chilli beef",
    "BBQ pit beans",
    "Chocolate ganache",
    "Walnut and goat's cheese salad with pomegranate dressing",
    "Cranachan pudding",
    "Panna cotta",
    "Tempura seafood",
    "Ham and cheese toastie",
    "Lemon custard tart",
    "Grilled salmon tacos",
    "Chicken and pesto pasta",
    "Ham and mustard crisps",
    "Coconut vanilla prawns",
    "Italian style goat's cheese pizza",
    "Vanilla panna cotta with pomegranate",
    "Chickpea curry",
    "Pork fajitas (with the works!)",
    "Orange and carrot cake with orange cream cheese icing",
    "Roasted pork loin with tropical fruit",
    "Nachos",
    "Cheddar cheese board",
    "Gazpacho soup",
    "Watercress rochfort and walnut salad",
    "Thai red curry",
    "Coarse pork pate with fresh crusty bread",
    "Beef burger topped with red onions and wasabi",
    "Maple jerky",
    "Sweet glazed ribs",
    "Pancakes with smokey bacon",
    "Rich vanilla ice cream. Neat (or make a float)",
    "Roast venison with a chocolate sauce",
    "The biggest darkest chocolate cake you can find",
    "PB&J sandwich",
    "Roast beef with a herb and malt crust",
    "Seriously sharp hard Cheddar",
    "Lamb and mint tagine",
    "Light and fluffy tangerine sponge cake",
    "Fresh green salad with avocados and pomegranate seeds",
    "Pizza with chili flakes",
    "Ginger and chocolate biscuits",
    "Spicy chorizo and prawn Jambalaya",
    "Jamaican Curry Goat",
    "Affogato with ice cream",
    "Green Thai curry",
    "Salmon with mango salsa",
    "Pho soup with light rice noodles",
    "Chilli covered burgers",
    "Roasted garlic Camembert",
    "Chocolate and walnut brownies",
    "Honey ham sandwich Gruyère cheese",
    "Steamed mussels",
    "Stilton and walnut salad",
    "Toffee caramel cheesecake",
    "Roast Chicken",
    "Spicy jalapeño and seared steak fajitas",
    "BBQ hot wings",
    "Pomegranate tart with walnuts",
    "Candied ginger pear cake",
    "Grilled lemon sole",
    "Fish tacos",
    "Monterey Jack stuffed grilled jalapeños",
    "Apple pie",
    "Roast chicken",
    "Seared steak",
    "Crusty bread",
    "Grilled chicken and steamed vegetables",
    "Pork sausages",
    "Seafood salad",
    "Sweet and sour pork",
    "Goat's cheese salad",
    "Pesto pasta",
    "Lemon cookies",
    "German Pretzels",
    "French Toast with Mixed Berries",
    "Blueberry Muffins",
    "Green Papaya Salad",
    "Seared Monkfish",
    "Cured Ham Ciabatta",
    "Eggs Benedict",
    "Chicken Liver Pâté",
    "Chocolate Mousse",
    "Scallops with Apricot Salsa",
    "Lemon and Thyme Roasted Chicken",
    "Raspberry Cheesecake with Mango Sorbet",
    "Chickpea Curry",
    "Orange Roast Chicken",
    "Turkish Delight",
    "Ceviche",
    "Raw Mango Raita",
    "Gathiya Waali Curry",
    "Chicken Tandoori",
    "Passionfruit Cheesecake",
    "Beef Jerky",
    "Steak with Blue Cheese Sauce",
    "Chocolate Lava Cake",
    "Prawn Pad Thai",
    "Solero",
    "Peach Cobbler",
    "Italian Espresso",
    "Smoky Chilli",
    "Biscotti",
    "Panna Cotta",
    "Fresh Muffins",
    "Ewes Curd",
    "Burnt Ends",
    "Jalapeño Poppers",
    "Blue Cheese",
    "Bunny Chow",
    "Lamb Potjiekos",
    "Cape Malay Koesisters",
    "Duck Gyoza",
    "Sweet and Sour Cauliflower",
    "Fourme D'ambert",
    "Chorizo",
    "Mexican Cheese Burgers",
    "Three Bean Salad",
    "Paneer Korma",
    "Potato and Cumin Salad",
    "Snickerdoodle",
    "Cream Cheese Crackers",
    "White Chocolate and Raspberry Cookies",
    "Birthday Cake",
    "Prawn Korma",
    "Coconut Ice",
    "Keylime Pie",
    "Profiteroles",
    "Shortbread",
    "Salmon and Avocado Tostadas",
    "Carrot Cake with Orange, Pistachio and Pomegranate",
    "Blueberry and Lemon Trifle",
    "Westcombe Dairy Cheddar",
    "Memphis-Style Beef Ribs",
    "Carrot Cake",
    "Étouffée",
    "Chilli-Shrimp Quesadilla",
    "Bakewell Tart",
    "Keen's Cheddar",
    "Green Mango Chutney",
    "Orange Pound Cake",
    "Kingstone Farm Rollright",
    "Porterhouse Steak",
    "Black Forest Gateau",
    "Marmalade Baked Camembert",
    "Blueberry and Yuzu Cheesecake",
    "Brie",
    "Chai Doughnuts",
    "Chocolate Ice Cream",
    "Chicken Choila",
    "Banana Fritter",
    "Connage Dunlop",
    "Alex James' Blue Monday #7",
    "Tiramisu",
    "Skate Wings in Black Butter",
    "Cajun-Spiced Pork Belly",
    "Vanilla-Root Ice Cream",
    "Goats Cheese and Rocket Pizza",
    "Vietnamese Lemongrass Chicken Curry",
    "Tart Au Citron with Thyme",
    "Barrel-Aged Feta Salad",
    "Avocado Toast",
    "Spiced Orange Tart",
    "Jalapeño and Cream Cheese Poppers",
    "Asparagus Pesto Pasta",
    "Bacon and Maple Syrup Cupcakes",
    "Chilean ChorIPAn",
    "Black Bean Tostadas with Avocado Salsa",
    "Sushi",
    "Sparkenhoe Red Leicester",
    "Huevos Rancheros",
    "Margherita Pizza",
    "Allondigas Meatballs",
    "Quadruple-Cheese Spätzle",
    "Bienenstich",
    "Spicy Honey-Roasted Cashew Nuts",
    "Dhaba-Style Punjabi Lamb Curry",
    "Pumpkin Roulade with Ginger Buttercream",
    "Godminster Vintage with Caramelised Cranberry Relish",
    "A Massive Ribeye Steak",
    "Mississippi Mud Pie",
    "Balsamic Glazed Chicken",
    "Brie and Goats Cheese Topped Pizza",
    "White Chocolate Cookies",
    "Moroccan Chicken Tagine",
    "Orange Blossom Madeleines",
    "Razor Clams with Sauce Verge",
    "Vietnamese Pho",
    "Buffalo Chicken Wings",
    "Manchego",
    "Vietnamese Tuna Burger",
    "Mango and Cardamom Syllabub",
    "Stoemp",
    "Bouillabaisse",
    "Oliebol",
    "Seared Ahi-Tuna Steaks",
    "Southern Fried Chicken",
    "Lemon Meringue Pie",
    "Salt + Pepper Tofu",
    "Melon Fruit Salad",
    "Lasagne",
    "Fried Chicken Sandwich",
    "Boston Cream Pie",
    "Dunbarton Blue Cheese",
    "Pasta Puttanesca",
    "Victoria Sponge",
    "Weisswurst with Mustard and Pretzels",
    "Smoky Lamb Rendang",
    "Lemon Cheesecake",
    "Goats Cheese and Caramelised Onion Tart",
    "Mild Blue Cheese",
    "Pork Ribs",
    "Game Pie",
    "Honey and Garlic Roasted Vegetables",
    "Toffee Apples",
    "Sugared Doughnuts",
    "Roasted Mango and Habanero Salsa",
    "Fish Tacos with Pickled Jalapeños",
    "Short Ribs",
    "Thai Shrimp Lettuce Wraps",
    "Sweet Potato and Coconut Dahl",
    "Flan De Coco",
    "Beef Stew",
    "Dark Chocolate",
    "Mole Poblano",
    "Black Bean Burrito",
    "Dal Makhani",
    "Sausages with Marmalade",
    "Mac 'n' Cheese with Crispy Pancetta",
    "Sausages",
    "Prune Drowned Pheasant",
    "Crème Brulee",
    "Parma Ham",
    "Clam Linguine",
    "Caesar Salad",
    "Tangy Coleslaw",
    "Hawaii 5-O Pizza",
    "Cajun Pork Chops",
    "Wild Boar Casserole",
    "BBQ Ribs",
    "Eton Mess",
    "Shot of Bourbon",
    "Apricot Wensleydale",
    "Jerk Chicken",
    "Ice Cream with Passionfruit",
    "Hoisin Duck",
    "Ricky Road Ice Cream",
    "Baked Honey Glazed Ham with Dark Fruit Sauce",
    "Herbal Roast Beef with Cranberry Jus",
    "Dark Fruitcake",
    "Long Clawson Stilton",
    "Tarta de Higos",
    "Caramelised Apple and Nutmeg Pie",
    "Bo Ssam",
    "Poutine",
    "Jam Doughnut",
    "Honey-Roasted Ham with Cranberry",
    "Sweet and Sticky BBQ Ribs",
    "New York Cheesecake",
    "Feta and Greens Salad with Citrus Dressing",
    "Fried Calamari",
    "Poached Eggs on Toast",
    "Lemon Thyme Roasted Chicken",
    "Packet of Nuts",
    "Bag of Crisps",
    "Ham and Cheese Toastie",
    "Strong Vintage Cheddar",
    "Haggis",
    "Dark Chili Chocolate",
    "Vintage Cheddar and Chutney",
    "Beef Bourguignon",
    "Apple Crumble with a Madagascan Vanilla Ice Cream",
    "Mimolette",
    "Almond Milk Pudding",
    "Pumpkin Cheesecake",
    "Roquefort",
    "Venison and Mushroom Stroganoff",
    "Orange Dark Chocolate",
    "Parmesan Baked Parsnips",
    "Lime Sorbet",
    "Spicy BBQ Seitan",
    "Aged Gouda",
    "Lamb Kofta",
    "Mushroom Tacos",
    "Thai Fishcakes",
    "Coconut Flour Blueberry Pancakes",
    "Roasted Red Pepper Hummus",
    "Garlic and Rosemary Focaccia",
    "Chicken Salad",
    "Ogleshield Jersey Cows Milk Cheese",
    "Cherry Cheesecake",
    "Seared Duck Breast",
    "Chili and Tomato Soup",
    "Red Wine and Spice Poached Quince with Mascarpone",
    "Goats Cheese Tart with caramelized Onions",
    "Mature Sharpham Elmhirst (English Brie)",
    "Spinach, Walnut and Blue Cheese Salad",
    "Moroccan Style Grilled Chicken and Cous Cous Salad",
    "Dorstone Ash Rolled Goats Cheese",
    "Coconut Cream Cake",
    "Tacos Al Pastor",
    "Ragstone Goats Log",
    "White Chocolate Cheesecake",
    "Radicchio Salad with Beans, Walnuts and Figs",
    "Soft Crofter's Cheese and Oat Cakes",
    "Belgian Mussels and Frites",
    "Moroccan Tagine",
    "Grilled Tilapia With Mango Salsa",
    "Golden-glazed Carrot, Mushroom & Hazelnut Tart",
    "Camembert",
    "Pheasant Breast",
    "Baked Goats Cheese",
    "Almond and Chocolate Tart",
    "Grilled Mackerel with Soy and Ginger Glaze",
    "Stichelton Creamy Blue Cheese",
    "5-Spice Duck Noodles"
];
